image: docker:latest
services:
  - docker:dind
cache:
  key: cache-global-key
  paths:
    - dist/
    - node_modules/

stages:
  - build
  - package
  - deploy

angular-build:
  image: docker.tele2.kz/ncp/angular-cli:latest
  stage: build
  before_script:
    - ssh-keyscan -H $SSH_SERVER_HOST >> ~/.ssh/known_hosts

  script:
    - export SSHPASS=$USER_PASS
    - sshpass -e scp ncp-frontend-app-deployment.yaml kube@$SSH_SERVER_HOST:/home/kube/ncp-frontend-app-deployment.yaml
    - npm install
    - ng build --configuration=production --base-href /ncp-frontend/ --output-hashing=all --prod=true
  artifacts:
    paths:
      - dist/*

docker-build:
  stage: package
  script:
    - docker build --cache-from $CI_REGISTRY_IMAGE:latest -t $CI_REGISTRY_IMAGE:latest .
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN docker.tele2.kz
    - docker push $CI_REGISTRY_IMAGE:latest

docker-deploy:
  stage: deploy
  image: ubuntu
  environment:
    name: development
  only:
  - master
  before_script:
    - apt update
    - apt install -y sshpass
    - sshpass -V
    - mkdir /root/.ssh
    - ssh-keyscan -H $SSH_SERVER_HOST >> ~/.ssh/known_hosts
  script:
  script:
    - export SSHPASS=$USER_PASS
    - sshpass -e ssh -T kube@$SSH_SERVER_HOST kubectl scale --replicas=0 deployment.apps/frontend-app -n ncp
    - sshpass -e ssh -T kube@$SSH_SERVER_HOST kubectl apply -f /home/kube/ncp-frontend-app-deployment.yaml
