apiVersion: v1
kind: PersistentVolume
metadata:
  name: frontend-app-alm-to-bp22-pv
spec:
  capacity:
    storage: 30Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-storage
  nfs:
    path: /data/nfs/frontend-app
    server: 10.200.200.22
    readOnly: false
