apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: frontend-app-pvc
  namespace: ncp
spec:
  storageClassName: nfs-storage
  accessModes:
  - ReadWriteMany
  resources:
     requests:
       storage: 20Gi
