version: "3.7"
services:
  ncp-ui:
    restart: always
    image: docker.tele2.kz/ncp/ncp-frontend-app:latest
    network_mode: bridge
    ports:
      - "4200:80"
    container_name: ncp-ui
    volumes:
      - "nfs-share:/var/log/nginx"
      - "nfs-share:/tmp"
volumes:
  nfs-share:
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=10.200.200.3,rw"
      device: ":/nfs/ncp/ncp-frontend-app/3"
